/**
 * What a crawler is allowed to index — §93.
 *
 * Pure, because the decision is subtle enough to be worth testing and because
 * getting it wrong is invisible: nothing errors, the pages simply stop ranking
 * or start competing with each other.
 *
 * ## The three rules, and why each exists
 *
 * 1. **Search results are `noindex`.** `?q=anything` is an unbounded set of
 *    URLs generated by visitors, each one a thin page of results that already
 *    exist elsewhere. Indexed, they dilute the pages that should rank and fill
 *    the crawl budget with noise.
 *
 * 2. **Deep facet combinations are `noindex`.** Four dimensions with a dozen
 *    terms each is a combinatorial space in the millions. One filter is a real
 *    page a person might link to; three at once is a crawl trap. The line is
 *    drawn at two.
 *
 * 3. **Page 2 and beyond self-canonicalise.** `rel=prev/next` was retired by
 *    Google in 2019, and canonicalising page 5 to page 1 tells the crawler
 *    those products do not exist. Each page points at itself and carries
 *    `noindex, follow` — the links are worth crawling, the page is not worth
 *    ranking.
 */

export interface RobotsDecision {
  index: boolean;
  follow: boolean;
  /** The URL this page claims as canonical, relative to the origin. */
  canonical: string;
  /** Why — surfaced in a comment so a reviewer does not have to re-derive it. */
  reason: string;
}

export interface SeoQuery {
  q?: string;
  category?: readonly string[];
  industry?: readonly string[];
  technology?: readonly string[];
  productType?: string;
  minPrice?: number;
  maxPrice?: number;
  customisable?: boolean;
  page: number;
}

const MAX_INDEXABLE_DIMENSIONS = 2;

export function robotsFor(basePath: string, query: SeoQuery): RobotsDecision {
  const dimensions = [
    query.category?.length ? 1 : 0,
    query.industry?.length ? 1 : 0,
    query.technology?.length ? 1 : 0,
    query.productType ? 1 : 0,
  ].reduce<number>((sum, value) => sum + value, 0);

  const hasPriceFilter = query.minPrice !== undefined || query.maxPrice !== undefined;

  if (query.q) {
    return {
      index: false,
      follow: true,
      // Search results canonicalise to the unfiltered listing: the products are
      // real, this particular slice of them is not a page.
      canonical: basePath,
      reason: "search results — unbounded, visitor-generated URLs",
    };
  }

  if (dimensions > MAX_INDEXABLE_DIMENSIONS || hasPriceFilter) {
    return {
      index: false,
      follow: true,
      canonical: basePath,
      reason: hasPriceFilter
        ? "price-filtered — the same products, sliced by a number"
        : `${dimensions} filter dimensions — combinatorial crawl trap`,
    };
  }

  if (query.page > 1) {
    return {
      index: false,
      follow: true,
      // Self-canonical, **not** page 1. Pointing page 5 at page 1 tells the
      // crawler that page 5's products do not exist anywhere.
      canonical: `${basePath}?page=${query.page}`,
      reason: "paginated — follow the links, don't rank the page",
    };
  }

  return {
    index: true,
    follow: true,
    canonical: basePath,
    reason: dimensions === 0 ? "the listing itself" : "a shallow, linkable filter",
  };
}

/** Shaped for Next's `Metadata.robots`. */
export function toMetadataRobots(decision: RobotsDecision) {
  return {
    index: decision.index,
    follow: decision.follow,
    googleBot: { index: decision.index, follow: decision.follow },
  };
}
